### ISSUE TITLE
arxiv GRID task failing in iterative mode 

### ISSUE THREAD

**Issue by russwinch** [nestauk/nesta#103]
database timeout error, potentially due to long lag between successful results and/or slower processing local processing inside the container.

A different python driver is used in the container- `mysql_connector_python` instead of `mysql_connector_repackaged`

A new session is created on the write step (where this error occurs), so it is strange this is timing out so quickly.

Investigate using longer timeout or connection pooling: https://docs.sqlalchemy.org/en/13/core/pooling.html#disconnect-handling-pessimistic

If it is failing before anything is written to the db, consider implementing `rollback()` and retrying.

**Comment by jaklinger** [comment]
could you not try reading the entire db in one go to generate a python lookup object? Depends on the size of the GRID data, but I'd assume that was ok

**Comment by russwinch** [comment]
it's weird because it's creating new `session` from the `engine` just to write the batch and this is where it is failing, all processed data is held in dictionaries until this point

**Comment by russwinch** [comment]
just checked and it runs fine outside the container, possibly because it runs quicker and the timeout isn't hit...not ideal setup really, I'll mess with some settings and see what happens, but it's helping me test at the moment, I don't need to keep deleting from `luigi_table_updates` 😄

**Comment by jaklinger** [comment]
incidentally the very first issue for this repo was to fix that (#3)

**Comment by russwinch** [comment]
unable to replicate this issue again after multiple runs 😞 possibly related to the data which was returned.
