### ISSUE TITLE
Typo in GtR table name

### ISSUE THREAD

**Issue by bishax** [nestauk/nesta#206]
https://github.com/nestauk/nesta/blob/5d73c749411d58c2c354b24421320da523d1e99d/nesta/core/orms/gtr_orm.py#L295

**Comment by bishax** [comment]
@kstathou what is this table used for?

**Comment by kstathou** [comment]
To store the document ID, the cluster number and the probability of being in that cluster of a GtR project.

That's part of the [clustering_task.py](https://github.com/nestauk/nesta/blob/154_clio_clusters/nesta/core/routines/embed_topics/clustering_task.py)

**Comment by bishax** [comment]
Ok, and does any code depend on this table that you are aware of?

**Comment by kstathou** [comment]
This tiny bit here: https://github.com/nestauk/nesta/blob/154_clio_clusters/nesta/core/routines/embed_topics/clustering_task.py#L86-L88

So changing the `__table_name__` shouldn't break anything.

**Comment by bishax** [comment]
Ok, and is there a reason that this is only in `dev` and not in `production`?

**Comment by kstathou** [comment]
I haven't run it on the full dataset. Joel also added #203 so it might be better to fix that first and then run it on production.

**Comment by jaklinger** [comment]
this will be address alongside #270
