### ISSUE TITLE
Investigate moving to AWS Cloudformation

### ISSUE THREAD

**Issue by mindrones** [nestauk/nesta#208]
We could move to AWS Cloudformation [1] so that we can manage the infrastructure with text files (JSON or YAML).

Pros:
- versioned infrastructure
- self-documented infrastructure (related [3])
- parts of the infrastructure easy to duplicate for testing/learning
- could be useful to check costs against setups

Cons:
- we'd need to learn (takes time) or hire a devOp [2]

[1] https://aws.amazon.com/cloudformation/
[2] https://aws.amazon.com/devops/
[3] https://github.com/nestauk/imt_playbook/issues/29

**Comment by jaklinger** [comment]
Agree this is the way to go. I'd opt for having this amongst a DevOps' responsibility.

**Comment by bishax** [comment]
Note: https://docs.aws.amazon.com/cdk/latest/guide/home.html drastically decreases the amount of tedious hand-written YAML required (cloudformation YAML configs are *large*)

**Comment by kstathou** [comment]
Check out [Terraform](https://www.terraform.io/), I've heard good things about it and it's also open source.

**Comment by jaklinger** [comment]
Moved to nestauk/daps_sandbox#10 as this will likely not get implemented in this version of DAPS
