### ISSUE TITLE
Neo4j: install `apoc`

### ISSUE THREAD

**Issue by mindrones** [nestauk/nesta#219]
We need to install `apoc` on the Neo4J instance of CORDIS[1], to do some database introspection [2] among other things.

[1] https://neo4j.com/docs/labs/apoc/current/introduction/#installation
[2] https://neo4j.com/docs/labs/apoc/current/database-introspection/meta/: `CALL apoc.meta.graph`

**Comment by porter22** [comment]
Installed APOC v3.4.0.7.
Steps:
1. Download *jar file from [here](https://neo4j.com/docs/labs/apoc/current/introduction/#installation): The first two digits of the version should match the current Neo4j version.
2. SSH to Neo4j server and place the *jar file into /var/lib/neo4j/plugins directory.
3. Add to the /etc/neo4j/neo4j.conf file the following line: `dbms.security.procedures.whitelist=apoc.coll.*,apoc.load.*`
4. Restart the Neo4j server using: `sudo systemctl stop neo4j`
5. Check whether APOC is working: `RETURN apoc.version()`

**Comment by mindrones** [comment]
@porter22 This is great thanks!

I'm getting an error when trying to use `CALL apoc.meta.graph` though [1].
I think setting

```
dbms.security.procedures.unrestricted=algo.*,apoc.*
```

and restart Neo4j could fix it.

[1]
```
Neo.ClientError.Procedure.ProcedureRegistrationFailed: apoc.meta.graph is unavailable because it is sandboxed and has dependencies outside of the sandbox. Sandboxing is controlled by the dbms.security.procedures.unrestricted setting. Only unrestrict procedures you can trust with access to database internals.
```

**Comment by porter22** [comment]
Fixed the APOC error: turns out there was a script that regenerates neo4j config file on restart.
The updated APOC installation steps are as follows:
1. Download *jar file from here: The first two digits of the version should match the current Neo4j version.
2. SSH to Neo4j server and place the *jar file into /var/lib/neo4j/plugins directory.
3. Edit the /etc/neo4j/neo4j.template the `dbms.security.procedures.unrestricted` parameter as follows: 
`dbms.security.procedures.unrestricted=algo.*, apoc.*`
4. Restart the Neo4j server using: `sudo systemctl stop neo4j`
5. Check whether APOC is working: `RETURN apoc.version()`

**Comment by mindrones** [comment]
Awesome well done! :)

`CALL apoc.meta.graph`:

<img width="1122" alt="Screenshot 2020-02-26 at 13 47 25" src="https://user-images.githubusercontent.com/1309648/75350518-91a7ed00-589e-11ea-8994-be976d8bb8b1.png">

**Entities**
```json
[{
    "name": "Datasets",
    "count": 3
  },
  {
    "name": "Organisation",
    "count": 51250
  },
  {
    "name": "Project",
    "count": 50640
  },
  {
    "name": "Proposal_Call",
    "count": 1102
  },
  {
    "name": "Publication",
    "count": 245465
  },
  {
    "name": "Report",
    "count": 34507
  },
  {
    "name": "Software",
    "count": 20
  },
  {
    "name": "Topic",
    "count": 6545
  }
]
```

**Relationships**
```json
[{
    "count": 632676,
    "type": "HAS_PROJECT",
    "in": 632676,
    "out": 51024
  },
  {
    "count": 51024,
    "type": "HAS_TOPIC",
    "in": 51024,
    "out": 51024
  },
  {
    "count": 251040,
    "type": "HAS_ORGANISATION",
    "in": 251040,
    "out": 251040
  },
  {
    "count": 632676,
    "type": "HAS_PROJECT",
    "in": 632676,
    "out": 34507
  },
  {
    "count": 245465,
    "type": "HAS_PUBLICATION",
    "in": 245465,
    "out": 245465
  },
  {
    "count": 632676,
    "type": "HAS_PROJECT",
    "in": 632676,
    "out": 50640
  },
  {
    "count": 50640,
    "type": "HAS_PROPOSAL_CALL",
    "in": 50640,
    "out": 50640
  },
  {
    "count": 34507,
    "type": "HAS_REPORT",
    "in": 34507,
    "out": 34507
  },
  {
    "count": 20,
    "type": "hasSoftware",
    "in": 20,
    "out": 20
  },
  {
    "count": 20,
    "type": "hasProject",
    "in": 20,
    "out": 20
  },
  {
    "count": 632676,
    "type": "HAS_PROJECT",
    "in": 632676,
    "out": 251040
  },
  {
    "count": 632676,
    "type": "HAS_PROJECT",
    "in": 632676,
    "out": 245465
  }
]
```
