### ISSUE TITLE
Neo4J: install an AWS certificate

### ISSUE THREAD

**Issue by mindrones** [nestauk/nesta#220]
When navigate to https://54.76.61.57:7473/browser we get the attached response as we need to install an AWS certificate to that endpoint.

<img width="667" alt="Screenshot 2020-02-13 at 14 20 14" src="https://user-images.githubusercontent.com/1309648/74444619-0a558500-4e6d-11ea-83c5-dada1585ff37.png">

**Comment by jaklinger** [comment]
This isn't a nesta DAPS or AWS issue, this is a EURITO DAPS issue. Moving to EURITO DAPS:

https://github.com/EURITO/eurito_daps/issues/27
