### ISSUE TITLE
Elasticsearch security

### ISSUE THREAD

**Issue by bishax** [nestauk/nesta#221]
https://phd.aws.amazon.com/phd/home#/event-log?Event%20ARN=arn:aws:health:eu-west-2::event/ES/AWS_ES_SECURITY_NOTIFICATION/AWS_ES_SECURITY_NOTIFICATION_3e0aa354-e7b4-4bb6-9aed-e6ba7d0e01b5&eventID=arn:aws:health:eu-west-2::event/ES/AWS_ES_SECURITY_NOTIFICATION/AWS_ES_SECURITY_NOTIFICATION_3e0aa354-e7b4-4bb6-9aed-e6ba7d0e01b5&eventTab=details&layout=vertical

Affects `eurito-dev` resource.
https://eu-west-2.console.aws.amazon.com/es/home?region=eu-west-2#domain:resource=eurito-dev;action=dashboard

- [ ] Determine resources to be accessed by anyone
- [ ] Confine these. E.g. arxlive has 
      ```
     {
      "Effect": "Allow",
      "Principal": {
        "AWS": "*"
      },
      "Action": [
        "es:ESHttpGet",
        "es:ESHttpPost"
      ],
      "Resource": [
        "arn:aws:es:eu-west-2:<accountno>:domain/arxlive/*/_search",
        "arn:aws:es:eu-west-2:<accountno>:domain/arxlive/*/_count",
        "arn:aws:es:eu-west-2:<accountno>:domain/arxlive/_aliases"
      ]
    }```

@porter22 is anybody currently consuming the indicators from elasticsearch (e.g. COTEC) using an AWS account or as "members of the public"?

**Comment by porter22** [comment]
I believe @Juan-Mateos was playing with ES over the last few days

**Comment by bishax** [comment]
Thinking about it, given that e.g. clio-lite is requests based, it will be as members of the public.
In that case, I propose restricting public access to `eurito-dev/*/_search`, `eurito-dev/*/_count`, and `eurito-dev/*/_aliases` in-line with other elastic-search access policies and the AWS guidelines.

This means indicators should still be able to be accessed but restricts modifying the data. 

Welcome alternatives/objections.

(cc. @mindrones )

**Comment by bishax** [comment]
I made the proposed changes.
