### ISSUE TITLE
Needs removing

### ISSUE THREAD

**Issue by danielbenton** [nestauk/nesta#321]
https://github.com/nestauk/nesta/blob/3382cbf248b08b04146e67497acc2e407972ddd4/nesta/core/nesta-config/luigi.cfg#L36

**Comment by jaklinger** [comment]
Hey @danielbenton, I think this is an old key since in the newer versions of the code base (since March) these files are all encrypted on github and so are invisible

**Comment by jaklinger** [comment]
It appears that this commit is Sept 2019, which I think was from the last time we had this issue so we rotated/changed the key
