### ISSUE TITLE
Meetup data processing for rwjf

### ISSUE THREAD

**Issue by jaklinger** [nestauk/nesta#96]
Relating to branch https://github.com/nestauk/nesta/tree/96-rwjf_mup

- [x] Devise method for automatic identification of health related meetup groups
- [x] Add local task for extracting topics relating to health
- [x] Add geocoding into pipeline
- [x] Pipe relevant meetup data to ES
- [x] Add `terms` alias for `terms_topics_group`
- [x] Add auto-translation
- [x] Sanitise html

Also related to #102

**Comment by jaklinger** [comment]
Index `meetup_v0` is now available https://search-health-scanner-5cs7g52446h7qscocqmiky5dn4.eu-west-2.es.amazonaws.com/meetup_v0/_search

**Comment by mindrones** [comment]
Closed by #122, moved the remaining points to #126
